// Mocks generated by Mockito 5.4.6 from annotations
// in saigonphantomlabs/test/widget/wifi_stressor_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i6;

import 'package:dio/dio.dart' as _i3;
import 'package:get/get.dart' as _i2;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:saigonphantomlabs/mckimquyen/widget/wifi_stressor/wifi_stressor_screen.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRxBool_0 extends _i1.SmartFake implements _i2.RxBool {
  _FakeRxBool_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRxInt_1 extends _i1.SmartFake implements _i2.RxInt {
  _FakeRxInt_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRxDouble_2 extends _i1.SmartFake implements _i2.RxDouble {
  _FakeRxDouble_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRxList_3<E> extends _i1.SmartFake implements _i2.RxList<E> {
  _FakeRxList_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRx_4<T> extends _i1.SmartFake implements _i2.Rx<T> {
  _FakeRx_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_5 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternalFinalCallback_6<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StressorController].
///
/// See the documentation for Mockito's code generation for more information.
class MockStressorController extends _i1.Mock
    implements _i4.StressorController {
  MockStressorController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RxBool get isRunning => (super.noSuchMethod(
        Invocation.getter(#isRunning),
        returnValue: _FakeRxBool_0(
          this,
          Invocation.getter(#isRunning),
        ),
      ) as _i2.RxBool);

  @override
  _i2.RxInt get downloadCount => (super.noSuchMethod(
        Invocation.getter(#downloadCount),
        returnValue: _FakeRxInt_1(
          this,
          Invocation.getter(#downloadCount),
        ),
      ) as _i2.RxInt);

  @override
  _i2.RxDouble get speedMbps => (super.noSuchMethod(
        Invocation.getter(#speedMbps),
        returnValue: _FakeRxDouble_2(
          this,
          Invocation.getter(#speedMbps),
        ),
      ) as _i2.RxDouble);

  @override
  _i2.RxDouble get totalSpeedMbps => (super.noSuchMethod(
        Invocation.getter(#totalSpeedMbps),
        returnValue: _FakeRxDouble_2(
          this,
          Invocation.getter(#totalSpeedMbps),
        ),
      ) as _i2.RxDouble);

  @override
  _i2.RxInt get parallelDownloads => (super.noSuchMethod(
        Invocation.getter(#parallelDownloads),
        returnValue: _FakeRxInt_1(
          this,
          Invocation.getter(#parallelDownloads),
        ),
      ) as _i2.RxInt);

  @override
  _i2.RxList<double> get speedHistory => (super.noSuchMethod(
        Invocation.getter(#speedHistory),
        returnValue: _FakeRxList_3<double>(
          this,
          Invocation.getter(#speedHistory),
        ),
      ) as _i2.RxList<double>);

  @override
  _i2.RxInt get totalDownloadedBytes => (super.noSuchMethod(
        Invocation.getter(#totalDownloadedBytes),
        returnValue: _FakeRxInt_1(
          this,
          Invocation.getter(#totalDownloadedBytes),
        ),
      ) as _i2.RxInt);

  @override
  _i2.Rx<Duration> get testDuration => (super.noSuchMethod(
        Invocation.getter(#testDuration),
        returnValue: _FakeRx_4<Duration>(
          this,
          Invocation.getter(#testDuration),
        ),
      ) as _i2.Rx<Duration>);

  @override
  _i2.Rx<DateTime?> get startTime => (super.noSuchMethod(
        Invocation.getter(#startTime),
        returnValue: _FakeRx_4<DateTime?>(
          this,
          Invocation.getter(#startTime),
        ),
      ) as _i2.Rx<DateTime?>);

  @override
  List<String> get urls => (super.noSuchMethod(
        Invocation.getter(#urls),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i3.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_5(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i3.Dio);

  @override
  _i2.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_6<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_6<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
      ) as int);

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startStressTest() => super.noSuchMethod(
        Invocation.method(
          #startStressTest,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopStressTest() => super.noSuchMethod(
        Invocation.method(
          #stopStressTest,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Disposer addListener(_i5.GetStateUpdate? listener) => (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
      ) as _i5.Disposer);

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListenerId(
    Object? id,
    _i6.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Disposer addListenerId(
    Object? key,
    _i5.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
      ) as _i5.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}
