// Mocks generated by Mockito 5.4.6 from annotations
// in saigonphantomlabs/test/unit/admob_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:google_mobile_ads/google_mobile_ads.dart' as _i2;
import 'package:google_mobile_ads/src/ad_inspector_containers.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:webview_flutter/webview_flutter.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInitializationStatus_0 extends _i1.SmartFake
    implements _i2.InitializationStatus {
  _FakeInitializationStatus_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRequestConfiguration_1 extends _i1.SmartFake
    implements _i2.RequestConfiguration {
  _FakeRequestConfiguration_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAdRequest_2 extends _i1.SmartFake implements _i2.AdRequest {
  _FakeAdRequest_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAdSize_3 extends _i1.SmartFake implements _i2.AdSize {
  _FakeAdSize_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBannerAdListener_4 extends _i1.SmartFake
    implements _i2.BannerAdListener {
  _FakeBannerAdListener_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInterstitialAdLoadCallback_5 extends _i1.SmartFake
    implements _i2.InterstitialAdLoadCallback {
  _FakeInterstitialAdLoadCallback_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRewardedAdLoadCallback_6 extends _i1.SmartFake
    implements _i2.RewardedAdLoadCallback {
  _FakeRewardedAdLoadCallback_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppOpenAdLoadCallback_7 extends _i1.SmartFake
    implements _i2.AppOpenAdLoadCallback {
  _FakeAppOpenAdLoadCallback_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MobileAds].
///
/// See the documentation for Mockito's code generation for more information.
class MockMobileAds extends _i1.Mock implements _i2.MobileAds {
  MockMobileAds() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.InitializationStatus> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<_i2.InitializationStatus>.value(
            _FakeInitializationStatus_0(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
      ) as _i3.Future<_i2.InitializationStatus>);

  @override
  _i3.Future<_i2.RequestConfiguration> getRequestConfiguration() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRequestConfiguration,
          [],
        ),
        returnValue: _i3.Future<_i2.RequestConfiguration>.value(
            _FakeRequestConfiguration_1(
          this,
          Invocation.method(
            #getRequestConfiguration,
            [],
          ),
        )),
      ) as _i3.Future<_i2.RequestConfiguration>);

  @override
  _i3.Future<void> updateRequestConfiguration(
          _i2.RequestConfiguration? requestConfiguration) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRequestConfiguration,
          [requestConfiguration],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setSameAppKeyEnabled(bool? isEnabled) => (super.noSuchMethod(
        Invocation.method(
          #setSameAppKeyEnabled,
          [isEnabled],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setAppMuted(bool? muted) => (super.noSuchMethod(
        Invocation.method(
          #setAppMuted,
          [muted],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setAppVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setAppVolume,
          [volume],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> disableSDKCrashReporting() => (super.noSuchMethod(
        Invocation.method(
          #disableSDKCrashReporting,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> disableMediationInitialization() => (super.noSuchMethod(
        Invocation.method(
          #disableMediationInitialization,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> getVersionString() => (super.noSuchMethod(
        Invocation.method(
          #getVersionString,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getVersionString,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> openDebugMenu(String? adUnitId) => (super.noSuchMethod(
        Invocation.method(
          #openDebugMenu,
          [adUnitId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> registerWebView(_i5.WebViewController? webViewController) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerWebView,
          [webViewController],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void openAdInspector(_i6.OnAdInspectorClosedListener? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #openAdInspector,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BannerAd].
///
/// See the documentation for Mockito's code generation for more information.
class MockBannerAd extends _i1.Mock implements _i2.BannerAd {
  MockBannerAd() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AdRequest get request => (super.noSuchMethod(
        Invocation.getter(#request),
        returnValue: _FakeAdRequest_2(
          this,
          Invocation.getter(#request),
        ),
      ) as _i2.AdRequest);

  @override
  _i2.AdSize get size => (super.noSuchMethod(
        Invocation.getter(#size),
        returnValue: _FakeAdSize_3(
          this,
          Invocation.getter(#size),
        ),
      ) as _i2.AdSize);

  @override
  _i2.BannerAdListener get listener => (super.noSuchMethod(
        Invocation.getter(#listener),
        returnValue: _FakeBannerAdListener_4(
          this,
          Invocation.getter(#listener),
        ),
      ) as _i2.BannerAdListener);

  @override
  bool get isMounted => (super.noSuchMethod(
        Invocation.getter(#isMounted),
        returnValue: false,
      ) as bool);

  @override
  String get adUnitId => (super.noSuchMethod(
        Invocation.getter(#adUnitId),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#adUnitId),
        ),
      ) as String);

  @override
  set responseInfo(_i2.ResponseInfo? value) => super.noSuchMethod(
        Invocation.setter(
          #responseInfo,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> load() => (super.noSuchMethod(
        Invocation.method(
          #load,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i2.AdSize?> getPlatformAdSize() => (super.noSuchMethod(
        Invocation.method(
          #getPlatformAdSize,
          [],
        ),
        returnValue: _i3.Future<_i2.AdSize?>.value(),
      ) as _i3.Future<_i2.AdSize?>);

  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [InterstitialAd].
///
/// See the documentation for Mockito's code generation for more information.
class MockInterstitialAd extends _i1.Mock implements _i2.InterstitialAd {
  MockInterstitialAd() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AdRequest get request => (super.noSuchMethod(
        Invocation.getter(#request),
        returnValue: _FakeAdRequest_2(
          this,
          Invocation.getter(#request),
        ),
      ) as _i2.AdRequest);

  @override
  _i2.InterstitialAdLoadCallback get adLoadCallback => (super.noSuchMethod(
        Invocation.getter(#adLoadCallback),
        returnValue: _FakeInterstitialAdLoadCallback_5(
          this,
          Invocation.getter(#adLoadCallback),
        ),
      ) as _i2.InterstitialAdLoadCallback);

  @override
  set fullScreenContentCallback(
          _i2.FullScreenContentCallback<_i2.InterstitialAd>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #fullScreenContentCallback,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onPaidEvent(_i2.OnPaidEventCallback? value) => super.noSuchMethod(
        Invocation.setter(
          #onPaidEvent,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get adUnitId => (super.noSuchMethod(
        Invocation.getter(#adUnitId),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#adUnitId),
        ),
      ) as String);

  @override
  set responseInfo(_i2.ResponseInfo? value) => super.noSuchMethod(
        Invocation.setter(
          #responseInfo,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> show() => (super.noSuchMethod(
        Invocation.method(
          #show,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setImmersiveMode(bool? immersiveModeEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setImmersiveMode,
          [immersiveModeEnabled],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [RewardedAd].
///
/// See the documentation for Mockito's code generation for more information.
class MockRewardedAd extends _i1.Mock implements _i2.RewardedAd {
  MockRewardedAd() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RewardedAdLoadCallback get rewardedAdLoadCallback => (super.noSuchMethod(
        Invocation.getter(#rewardedAdLoadCallback),
        returnValue: _FakeRewardedAdLoadCallback_6(
          this,
          Invocation.getter(#rewardedAdLoadCallback),
        ),
      ) as _i2.RewardedAdLoadCallback);

  @override
  set fullScreenContentCallback(
          _i2.FullScreenContentCallback<_i2.RewardedAd>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #fullScreenContentCallback,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onUserEarnedRewardCallback(_i2.OnUserEarnedRewardCallback? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #onUserEarnedRewardCallback,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onPaidEvent(_i2.OnPaidEventCallback? value) => super.noSuchMethod(
        Invocation.setter(
          #onPaidEvent,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get adUnitId => (super.noSuchMethod(
        Invocation.getter(#adUnitId),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#adUnitId),
        ),
      ) as String);

  @override
  set responseInfo(_i2.ResponseInfo? value) => super.noSuchMethod(
        Invocation.setter(
          #responseInfo,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> show(
          {required _i2.OnUserEarnedRewardCallback? onUserEarnedReward}) =>
      (super.noSuchMethod(
        Invocation.method(
          #show,
          [],
          {#onUserEarnedReward: onUserEarnedReward},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setServerSideOptions(
          _i2.ServerSideVerificationOptions? options) =>
      (super.noSuchMethod(
        Invocation.method(
          #setServerSideOptions,
          [options],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setImmersiveMode(bool? immersiveModeEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setImmersiveMode,
          [immersiveModeEnabled],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [AppOpenAd].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppOpenAd extends _i1.Mock implements _i2.AppOpenAd {
  MockAppOpenAd() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppOpenAdLoadCallback get adLoadCallback => (super.noSuchMethod(
        Invocation.getter(#adLoadCallback),
        returnValue: _FakeAppOpenAdLoadCallback_7(
          this,
          Invocation.getter(#adLoadCallback),
        ),
      ) as _i2.AppOpenAdLoadCallback);

  @override
  set fullScreenContentCallback(
          _i2.FullScreenContentCallback<_i2.AppOpenAd>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #fullScreenContentCallback,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onPaidEvent(_i2.OnPaidEventCallback? value) => super.noSuchMethod(
        Invocation.setter(
          #onPaidEvent,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get adUnitId => (super.noSuchMethod(
        Invocation.getter(#adUnitId),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#adUnitId),
        ),
      ) as String);

  @override
  set responseInfo(_i2.ResponseInfo? value) => super.noSuchMethod(
        Invocation.setter(
          #responseInfo,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> show() => (super.noSuchMethod(
        Invocation.method(
          #show,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setImmersiveMode(bool? immersiveModeEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setImmersiveMode,
          [immersiveModeEnabled],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
